name: treasurehunt
description: A Treasure Hunt Game for CodersUK


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^1.0.0
  cupertino_icons: ^0.1.2
  location: ^2.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  #  Firebase
  #  https://pub.dev/packages/firebase_core#-installing-tab-
  firebase_core: ^0.4.0+1
  #  Firebase database : https://pub.dev/packages/firebase_database#-installing-tab-
  firebase_database: ^3.0.0
  # Firebase storage : https://pub.dev/packages/firebase_storage#-installing-tab-
  firebase_storage: ^3.0.0
  #  Firebase Authentication : https://pub.dev/packages/firebase_auth#-installing-tab-
  firebase_auth: ^0.11.1
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
